export type Orientation = 'landscape' | 'portrait' | 'square' | 'panorama'

/** Editorial collection personality — all fields optional. */
export type CollectionMeta = {
  title?: string
  description?: string
  location?: string
  dateRange?: string
  photographer?: string
  /** Public path to a cover image, e.g. `/gallery/cover.jpg` */
  coverImage?: string
}

/**
 * One photograph in the collection.
 * Generated by the gallery manifest Vite plugin — do not hand-author.
 */
export type GalleryItem = {
  id: string
  /** Public URL path, e.g. `/gallery/folder/photo.jpg` */
  src: string
  filename: string
  /** Path relative to `public/gallery/`, using `/` separators */
  relativePath: string
  width: number
  height: number
  orientation: Orientation
  /** width / height */
  aspectRatio: number
  bytes: number
  /** Filesystem mtime as Unix epoch milliseconds */
  mtime: number
}

export type ManifestMetadata = {
  /** Schema version for future migrations */
  version: 1
  generatedAt: string
  itemCount: number
}

export type GalleryManifest = {
  meta: ManifestMetadata
  collection: CollectionMeta
  items: GalleryItem[]
}

export type ManifestWarningCode =
  | 'duplicate-id'
  | 'invalid-filename'
  | 'unsupported-format'
  | 'missing-file'
  | 'invalid-dimensions'
  | 'invalid-manifest'

export type ManifestWarning = {
  code: ManifestWarningCode
  message: string
  path?: string
}
